class Commands(object):
    LEFT_THUMBSTICK_HORIZONTAL = 1
    LEFT_THUMBSTICK_VERTICAL = 2
    RIGHT_THUMBSTICK_HORIZONTAL = 3
    RIGHT_THUMBSTICK_VERTICAL = 4
    BUTTON_PRESSED = 5
    BUTTON_RELEASED = 6
    KEEP_ALIVE = 20
    POP_WAYPOINT = 21

THUMBSTICK_COMMANDS = set((
    Commands.LEFT_THUMBSTICK_HORIZONTAL,
    Commands.LEFT_THUMBSTICK_VERTICAL,
    Commands.RIGHT_THUMBSTICK_HORIZONTAL,
    Commands.RIGHT_THUMBSTICK_VERTICAL,
))
